permissions:
  issues: write

name: Nuclei - Vulnerability Scan

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - 'https://juice-shop.herokuapp.com/'
          - 'https://comprovante.pagseguro.uol.com.br/'
          - 'https://pagseguro.uol.com.br/'
          - 'http://pagvendas.pagseguro.uol.com.br/'
          - 'https://clube.pagseguro.uol.com.br/portal/login'
    steps:
      - uses: actions/checkout@v2

      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: ${{ matrix.target }}
          flags: "-severity critical,high,medium,low -stats"
          github-report: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log

      - name: GitHub Security Dashboard Alerts update
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: nuclei.sarif
